apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: fint-kontroll-access-management-play
  name: fint-kontroll-access-management-play
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: fint-kontroll-access-management-play
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-kontroll-access-management-play
  name: fint-kontroll-access-management-play
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-kontroll-access-management-play
  template:
    metadata:
      labels:
        io.kompose.service: fint-kontroll-access-management-play
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/fint-kontroll-access-management-play:build.${BUILD_NUMBER}_${GIT_COMMIT}
          name: fint-kontroll-access-management-play
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc'
