apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
patchesStrategicMerge:
  - config-map.yaml
commonLabels:
  app.kubernetes.io/name: fint-kontroll-access-management-play
  app.kubernetes.io/instance: fint-kontroll-access-management-play_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no

