apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-kontroll-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fint-kontroll-opa
  template:
    metadata:
      labels:
        app: fint-kontroll-opa
    spec:
      containers:
        - name: fint-kontroll-opa
          image: openpolicyagent/opa:latest
          ports:
            - name: http
              containerPort: 8181
          args:
            - "run"
            - "--server"
            - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
            - "--log-level=info"
            - "--set=decision_logs.console=true"
            - "--set=bundles.main.resource=/bundles/main.tar.gz"
            - "--set=services.main.url=http://fint-kontroll-opa-bundle-server"
            - "--set=bundles.main.polling.min_delay_seconds=10"
            - "--set=bundles.main.polling.max_delay_seconds=20"
