apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais.yaml
commonLabels:
  app.kubernetes.io/name: fint-kontroll-access-management-play
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: access-management-play
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no

patches:
  - path: opa.patch.yaml
    target:
      kind: Application
