apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais.yaml
  - deployment-opa.yaml
  - service-opa.yaml
commonLabels:
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no

#patches:
#  - path: opa.patch.yaml
#    target:
#      kind: Deployment
#      name: fint-kontroll-access-management-play
