apiVersion: v1
kind: Pod
metadata:
  name: opa-sidecar
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:latest
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8181"
        - "--log-level=info"
