apiVersion: fintlabs.no/v1alpha1
kind: Deployment
metadata:
  name: opa-sidecar
spec:
  template:
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=localhost:8181"
            - "--log-level=info"
